Repository mybatis/mybatis-3, pull requests merged in 2019-07, with the labels that each got.

#1574 Change in documentation
  src/site/es/xdoc/dynamic-sql.xml
  src/site/es/xdoc/java-api.xml
  src/site/ja/xdoc/dynamic-sql.xml
  src/site/ja/xdoc/java-api.xml
  src/site/ko/xdoc/dynamic-sql.xml
  src/site/ko/xdoc/java-api.xml
  src/site/xdoc/dynamic-sql.xml
  src/site/xdoc/java-api.xml
  src/site/zh/xdoc/dynamic-sql.xml
  src/site/zh/xdoc/java-api.xml
Labels: waiting for feedback

#1248 Support default method
  src/main/java/org/apache/ibatis/cache/Cache.java
  src/main/java/org/apache/ibatis/cache/decorators/BlockingCache.java
  src/main/java/org/apache/ibatis/cache/decorators/FifoCache.java
  src/main/java/org/apache/ibatis/cache/decorators/LoggingCache.java
  src/main/java/org/apache/ibatis/cache/decorators/LruCache.java
  src/main/java/org/apache/ibatis/cache/decorators/ScheduledCache.java
  src/main/java/org/apache/ibatis/cache/decorators/SerializedCache.java
  src/main/java/org/apache/ibatis/cache/decorators/SoftCache.java
  src/main/java/org/apache/ibatis/cache/decorators/SynchronizedCache.java
  src/main/java/org/apache/ibatis/cache/decorators/TransactionalCache.java
  src/main/java/org/apache/ibatis/cache/decorators/WeakCache.java
  src/main/java/org/apache/ibatis/cache/impl/PerpetualCache.java
  src/main/java/org/apache/ibatis/executor/loader/ProxyFactory.java
  src/main/java/org/apache/ibatis/executor/loader/cglib/CglibProxyFactory.java
  src/main/java/org/apache/ibatis/executor/loader/javassist/JavassistProxyFactory.java
  src/main/java/org/apache/ibatis/mapping/DatabaseIdProvider.java
  src/main/java/org/apache/ibatis/plugin/Interceptor.java
  src/main/java/org/apache/ibatis/reflection/factory/DefaultObjectFactory.java
  src/main/java/org/apache/ibatis/reflection/factory/ObjectFactory.java
  src/main/java/org/apache/ibatis/transaction/TransactionFactory.java
  src/main/java/org/apache/ibatis/transaction/jdbc/JdbcTransactionFactory.java
  src/site/es/xdoc/configuration.xml
  src/site/ja/xdoc/configuration.xml
  src/site/ko/xdoc/configuration.xml
  src/site/xdoc/configuration.xml
  src/site/zh/xdoc/configuration.xml
  src/test/java/org/apache/ibatis/plugin/PluginTest.java
  src/test/java/org/apache/ibatis/submitted/custom_collection_handling/CustomObjectFactory.java
Labels: enhancement

#1522 Add value attribute on provider annotations
  src/main/java/org/apache/ibatis/annotations/DeleteProvider.java
  src/main/java/org/apache/ibatis/annotations/InsertProvider.java
  src/main/java/org/apache/ibatis/annotations/SelectProvider.java
  src/main/java/org/apache/ibatis/annotations/UpdateProvider.java
  src/main/java/org/apache/ibatis/builder/annotation/ProviderSqlSource.java
  src/site/es/xdoc/java-api.xml
  src/site/ja/xdoc/java-api.xml
  src/site/ko/xdoc/java-api.xml
  src/site/xdoc/java-api.xml
  src/site/zh/xdoc/java-api.xml
  src/test/java/org/apache/ibatis/submitted/sqlprovider/ProviderMethodResolutionTest.java
  src/test/java/org/apache/ibatis/submitted/sqlprovider/SqlProviderTest.java
Labels: enhancement

#1591 fix Japanese document in logging.xml
  src/site/ja/xdoc/logging.xml
Labels: documentation

#1592 Upgrade to JUnit 5.5
  pom.xml
Labels: polishing

#1056 Add defaultResultSetType as global configuration
  src/main/java/org/apache/ibatis/builder/annotation/MapperAnnotationBuilder.java
  src/main/java/org/apache/ibatis/builder/xml/XMLConfigBuilder.java
  src/main/java/org/apache/ibatis/builder/xml/XMLStatementBuilder.java
  src/main/java/org/apache/ibatis/session/Configuration.java
  src/site/es/xdoc/configuration.xml
  src/site/ja/xdoc/configuration.xml
  src/site/ko/xdoc/configuration.xml
  src/site/xdoc/configuration.xml
  src/site/zh/xdoc/configuration.xml
  src/test/java/org/apache/ibatis/builder/AnnotationMapperBuilderTest.java
  src/test/java/org/apache/ibatis/builder/CustomizedSettingsMapperConfig.xml
  src/test/java/org/apache/ibatis/builder/XmlConfigBuilderTest.java
  src/test/java/org/apache/ibatis/builder/XmlMapperBuilderTest.java
Labels: enhancement

#1604 Support to assign single primitive parameter on SQL provider method
  src/main/java/org/apache/ibatis/builder/annotation/ProviderSqlSource.java
  src/test/java/org/apache/ibatis/submitted/sqlprovider/Mapper.java
  src/test/java/org/apache/ibatis/submitted/sqlprovider/OurSqlBuilder.java
  src/test/java/org/apache/ibatis/submitted/sqlprovider/SqlProviderTest.java
Labels: bug

#1611 Add constructor that pass an Annotation type instead of Object on ProviderSqlSource
  src/main/java/org/apache/ibatis/builder/annotation/ProviderSqlSource.java
  src/test/java/org/apache/ibatis/submitted/sqlprovider/SqlProviderTest.java
Labels: polishing

#1615 Support variable substitution in CDATA of included `<sql />`
  src/main/java/org/apache/ibatis/builder/xml/XMLIncludeTransformer.java
  src/test/java/org/apache/ibatis/submitted/include_property/Mapper.xml
Labels: enhancement

#1618 Change to Constructor#newInstance from Class#newInstance
  src/main/java/org/apache/ibatis/builder/BaseBuilder.java
  src/main/java/org/apache/ibatis/builder/annotation/ProviderSqlSource.java
  src/main/java/org/apache/ibatis/builder/xml/XMLConfigBuilder.java
  src/main/java/org/apache/ibatis/datasource/unpooled/UnpooledDataSource.java
  src/main/java/org/apache/ibatis/io/VFS.java
  src/test/java/org/apache/ibatis/builder/XmlMapperBuilderTest.java
  src/test/java/org/apache/ibatis/exceptions/GeneralExceptionsTest.java
Labels: polishing
