Repository mybatis/mybatis-3, pull requests merged in 2019-01, with the labels that each got.

#1430 Removed unnecessary ordering from cursor tests and updated comments
  src/main/java/org/apache/ibatis/cursor/Cursor.java
  src/test/java/org/apache/ibatis/submitted/cursor_simple/Mapper.xml
Labels: documentation

#1437 OffsetTimeTypeHandler should use setObject(), getObject()
  src/main/java/org/apache/ibatis/type/OffsetTimeTypeHandler.java
  src/test/java/org/apache/ibatis/submitted/timestamp_with_timezone/Mapper.java
  src/test/java/org/apache/ibatis/submitted/timestamp_with_timezone/Record.java
  src/test/java/org/apache/ibatis/submitted/timestamp_with_timezone/TimestampWithTimezoneTypeHandlerTest.java
  src/test/java/org/apache/ibatis/type/OffsetTimeTypeHandlerTest.java
Labels: bug

#1438 ZonedDateTimeTypeHandler should use setObject(), getObject()
  src/main/java/org/apache/ibatis/type/ZonedDateTimeTypeHandler.java
  src/test/java/org/apache/ibatis/type/ZonedDateTimeTypeHandlerTest.java
Labels: bug

#1447 Removing not necessary argument in method indexOf
  src/main/java/org/apache/ibatis/parsing/GenericTokenParser.java
Labels: enhancement

#1454 Change to use the diamond operator
  src/main/java/org/apache/ibatis/binding/MapperRegistry.java
  src/main/java/org/apache/ibatis/builder/MapperBuilderAssistant.java
  src/main/java/org/apache/ibatis/builder/annotation/ProviderSqlSource.java
  src/main/java/org/apache/ibatis/scripting/defaults/RawSqlSource.java
  src/test/java/org/apache/ibatis/binding/FlushTest.java
  src/test/java/org/apache/ibatis/binding/MapperMethodParamTest.java
  src/test/java/org/apache/ibatis/builder/XmlConfigBuilderTest.java
  src/test/java/org/apache/ibatis/builder/xml/dynamic/DynamicSqlSourceTest.java
  src/test/java/org/apache/ibatis/builder/xsd/XmlConfigBuilderTest.java
  src/test/java/org/apache/ibatis/cache/BaseCacheTest.java
  src/test/java/org/apache/ibatis/datasource/jndi/JndiDataSourceFactoryTest.java
  src/test/java/org/apache/ibatis/domain/jpetstore/Cart.java
  src/test/java/org/apache/ibatis/domain/jpetstore/Order.java
  src/test/java/org/apache/ibatis/executor/ExecutorTestHelper.java
  src/test/java/org/apache/ibatis/executor/loader/CglibProxyTest.java
  src/test/java/org/apache/ibatis/executor/loader/JavassistProxyTest.java
  src/test/java/org/apache/ibatis/executor/loader/SerializableProxyTest.java
  src/test/java/org/apache/ibatis/jdbc/PooledDataSourceTest.java
  src/test/java/org/apache/ibatis/mapping/BoundSqlTest.java
  src/test/java/org/apache/ibatis/parsing/GenericTokenParserTest.java
  src/test/java/org/apache/ibatis/reflection/MetaObjectTest.java
  src/test/java/org/apache/ibatis/submitted/bringrags/SimpleObject.java
  src/test/java/org/apache/ibatis/submitted/collectionparameters/CollectionParametersTest.java
  src/test/java/org/apache/ibatis/submitted/complex_type/ComplexTypeTest.java
  src/test/java/org/apache/ibatis/submitted/cursor_simple/CursorSimpleTest.java
  src/test/java/org/apache/ibatis/submitted/custom_collection_handling/CustomCollection.java
  src/test/java/org/apache/ibatis/submitted/deferload_common_property/CommonPropertyDeferLoadError.java
  src/test/java/org/apache/ibatis/submitted/dynsql/DynSqlTest.java
  src/test/java/org/apache/ibatis/submitted/dynsql2/DynSqlTest.java
  src/test/java/org/apache/ibatis/submitted/extends_with_constructor/StudentConstructor.java
  src/test/java/org/apache/ibatis/submitted/foreach/ForEachTest.java
  src/test/java/org/apache/ibatis/submitted/foreach_map/MapParam.java
  src/test/java/org/apache/ibatis/submitted/generictypes/UserTypeHandler.java
  src/test/java/org/apache/ibatis/submitted/hashmaptypehandler/HashMapTypeHandlerTest.java
  src/test/java/org/apache/ibatis/submitted/heavy_initial_load/HeavyInitialLoadTest.java
  src/test/java/org/apache/ibatis/submitted/include_property/IncludePropertyTest.java
  src/test/java/org/apache/ibatis/submitted/initialized_collection_property/Author.java
  src/test/java/org/apache/ibatis/submitted/keygen/Jdbc3KeyGeneratorTest.java
  src/test/java/org/apache/ibatis/submitted/language/LanguageTest.java
  src/test/java/org/apache/ibatis/submitted/language/VelocitySqlSource.java
  src/test/java/org/apache/ibatis/submitted/language/VelocitySqlSourceBuilder.java
  src/test/java/org/apache/ibatis/submitted/lazy_properties/LazyPropertiesTest.java
  src/test/java/org/apache/ibatis/submitted/maptypehandler/MapTypeHandlerTest.java
  src/test/java/org/apache/ibatis/submitted/nested/Name.java
  src/test/java/org/apache/ibatis/submitted/nested/NestedForEachTest.java
  src/test/java/org/apache/ibatis/submitted/nested/Parameter.java
  src/test/java/org/apache/ibatis/submitted/nestedresulthandler/Person.java
  src/test/java/org/apache/ibatis/submitted/nestedresulthandler_association/NestedResultHandlerAssociationTest.java
  src/test/java/org/apache/ibatis/submitted/permissions/Principal.java
  src/test/java/org/apache/ibatis/submitted/permissions/Resource.java
  src/test/java/org/apache/ibatis/submitted/refcursor/RefCursorTest.java
  src/test/java/org/apache/ibatis/submitted/result_handler/UserResultHandler.java
  src/test/java/org/apache/ibatis/submitted/selectkey/SelectKeyTest.java
  src/test/java/org/apache/ibatis/submitted/sptests/SPTest.java
  src/test/java/org/apache/ibatis/submitted/sqlprovider/SqlProviderTest.java
  src/test/java/org/apache/ibatis/submitted/typehandlerinjection/TypeHandlerInjectionTest.java
  src/test/java/org/apache/ibatis/submitted/typehandlerinjection/UserStateTypeHandler.java
  src/test/java/org/apache/ibatis/submitted/valueinmap/ValueInMapTest.java
Labels: enhancement

#1461 Change class name at some testcase classes
  src/test/java/org/apache/ibatis/submitted/deferload_common_property/CommonPropertyDeferLoadTest.java
  src/test/java/org/apache/ibatis/submitted/lazyload_common_property/CommonPropertyLazyLoadTest.java
  src/test/java/org/apache/ibatis/submitted/order_prefix_removed/OrderPrefixRemovedTest.java
Labels: enhancement

#1463 Change to use the StringJoiner instead of the StringBuilder
  src/main/java/org/apache/ibatis/builder/annotation/MapperAnnotationBuilder.java
  src/main/java/org/apache/ibatis/cache/CacheKey.java
  src/main/java/org/apache/ibatis/logging/jdbc/ResultSetLogger.java
  src/main/java/org/apache/ibatis/reflection/factory/DefaultObjectFactory.java
  src/main/java/org/apache/ibatis/scripting/xmltags/DynamicContext.java
Labels: enhancement

#1467 Polishing codes
  src/main/java/org/apache/ibatis/builder/xml/XMLIncludeTransformer.java
  src/main/java/org/apache/ibatis/logging/jdbc/BaseJdbcLogger.java
  src/main/java/org/apache/ibatis/logging/jdbc/ResultSetLogger.java
  src/main/java/org/apache/ibatis/reflection/ParamNameUtil.java
  src/main/java/org/apache/ibatis/reflection/Reflector.java
  src/main/java/org/apache/ibatis/scripting/xmltags/DynamicSqlSource.java
  src/main/java/org/apache/ibatis/scripting/xmltags/MixedSqlNode.java
Labels: enhancement

#1468 remove redundant extends object
  src/main/java/org/apache/ibatis/executor/result/DefaultResultHandler.java
  src/main/java/org/apache/ibatis/type/UnknownTypeHandler.java
Labels: enhancement

#1470 use removeIf and list.sort to polish code
  src/main/java/org/apache/ibatis/builder/MapperBuilderAssistant.java
  src/main/java/org/apache/ibatis/mapping/ResultMap.java
Labels: enhancement

#1471 collapse identical catch
  src/main/java/org/apache/ibatis/io/VFS.java
  src/main/java/org/apache/ibatis/logging/slf4j/Slf4jImpl.java
  src/main/java/org/apache/ibatis/scripting/defaults/DefaultParameterHandler.java
Labels: enhancement

#1472 Ambiguous collection type bug fix. Ref #364
  src/main/java/org/apache/ibatis/builder/xml/XMLMapperBuilder.java
  src/test/java/org/apache/ibatis/submitted/stringlist/StringListTest.java
Labels: bug
