Repository mybatis/mybatis-3, pull requests merged in 2019-09, with the labels that each got.

#1629 Fix some sonar reports
  src/main/java/org/apache/ibatis/cache/CacheKey.java
  src/main/java/org/apache/ibatis/cache/NullCacheKey.java
  src/main/java/org/apache/ibatis/io/DefaultVFS.java
  src/main/java/org/apache/ibatis/parsing/XPathParser.java
Labels: polishing

#1649 [doc] Update namespace of class Cache
  src/site/es/xdoc/sqlmap-xml.xml
  src/site/ja/xdoc/sqlmap-xml.xml
  src/site/ko/xdoc/sqlmap-xml.xml
  src/site/zh/xdoc/sqlmap-xml.xml
Labels: documentation

#1659 Remove redundant null check in VFSHolder
  src/main/java/org/apache/ibatis/io/VFS.java
Labels: polishing

#1662 Remove several redundant operations
  src/main/java/org/apache/ibatis/mapping/ResultMapping.java
  src/main/java/org/apache/ibatis/mapping/SqlCommandType.java
  src/main/java/org/apache/ibatis/session/defaults/DefaultSqlSession.java
Labels: polishing

#1667 typofix: change SqlSession to SqlSessionFactory
  src/site/es/xdoc/java-api.xml
  src/site/ja/xdoc/java-api.xml
  src/site/ko/xdoc/java-api.xml
  src/site/xdoc/java-api.xml
  src/site/zh/xdoc/java-api.xml
Labels: documentation, waiting for feedback

#1670 Translated the untranslated sentence in the Chinese document
  src/site/zh/xdoc/dynamic-sql.xml
Labels: documentation

#1673 refactor: typo fix in CacheKey.java
  src/main/java/org/apache/ibatis/cache/CacheKey.java
Labels: polishing

#1672 promote 1000 to long
  src/main/java/org/apache/ibatis/cache/decorators/ScheduledCache.java
Labels: polishing

#1660 format XNode toString method.
  src/main/java/org/apache/ibatis/parsing/XNode.java
  src/test/java/org/apache/ibatis/parsing/XPathParserTest.java
Labels: waiting for feedback

#1676 Fix grammatical mistakes and add more <code> tags in English documentation
  src/site/xdoc/configuration.xml
  src/site/xdoc/java-api.xml
Labels: documentation

#1666 use SqlSession instead of SqlSessions
  src/site/zh/xdoc/java-api.xml
Labels: documentation

#1675 Remove unnecessary code.
  src/main/java/org/apache/ibatis/executor/statement/StatementUtil.java
Labels: polishing

#1671 add the synchronized keyword to getDriver()
  src/main/java/org/apache/ibatis/datasource/unpooled/UnpooledDataSource.java
Labels: polishing
