Repository mybatis/mybatis-3, pull requests merged in 2019-10, with the labels that each got.

#1689 refactor: remove unnecessary code.
  src/main/java/org/apache/ibatis/executor/keygen/SelectKeyGenerator.java
Labels: polishing

#1696 Add javadoc for annotations
  src/main/java/org/apache/ibatis/annotations/Arg.java
  src/main/java/org/apache/ibatis/annotations/CacheNamespace.java
  src/main/java/org/apache/ibatis/annotations/Case.java
  src/main/java/org/apache/ibatis/annotations/ConstructorArgs.java
  src/main/java/org/apache/ibatis/annotations/Delete.java
  src/main/java/org/apache/ibatis/annotations/DeleteProvider.java
  src/main/java/org/apache/ibatis/annotations/Insert.java
  src/main/java/org/apache/ibatis/annotations/InsertProvider.java
  src/main/java/org/apache/ibatis/annotations/Lang.java
  src/main/java/org/apache/ibatis/annotations/Many.java
  src/main/java/org/apache/ibatis/annotations/MapKey.java
  src/main/java/org/apache/ibatis/annotations/One.java
  src/main/java/org/apache/ibatis/annotations/Options.java
  src/main/java/org/apache/ibatis/annotations/Param.java
  src/main/java/org/apache/ibatis/annotations/Result.java
  src/main/java/org/apache/ibatis/annotations/ResultMap.java
  src/main/java/org/apache/ibatis/annotations/ResultType.java
  src/main/java/org/apache/ibatis/annotations/Results.java
  src/main/java/org/apache/ibatis/annotations/Select.java
  src/main/java/org/apache/ibatis/annotations/SelectKey.java
  src/main/java/org/apache/ibatis/annotations/SelectProvider.java
  src/main/java/org/apache/ibatis/annotations/TypeDiscriminator.java
  src/main/java/org/apache/ibatis/annotations/Update.java
  src/main/java/org/apache/ibatis/annotations/UpdateProvider.java
  src/main/java/org/apache/ibatis/plugin/Intercepts.java
  src/main/java/org/apache/ibatis/plugin/Signature.java
  src/main/java/org/apache/ibatis/type/Alias.java
  src/main/java/org/apache/ibatis/type/MappedJdbcTypes.java
  src/main/java/org/apache/ibatis/type/MappedTypes.java
Labels: documentation

#1697 Improve JavaDoc for annotations
  src/main/java/org/apache/ibatis/annotations/Arg.java
  src/main/java/org/apache/ibatis/annotations/AutomapConstructor.java
  src/main/java/org/apache/ibatis/annotations/CacheNamespace.java
  src/main/java/org/apache/ibatis/annotations/CacheNamespaceRef.java
  src/main/java/org/apache/ibatis/annotations/Case.java
  src/main/java/org/apache/ibatis/annotations/ConstructorArgs.java
  src/main/java/org/apache/ibatis/annotations/Delete.java
  src/main/java/org/apache/ibatis/annotations/DeleteProvider.java
  src/main/java/org/apache/ibatis/annotations/Flush.java
  src/main/java/org/apache/ibatis/annotations/Insert.java
  src/main/java/org/apache/ibatis/annotations/InsertProvider.java
  src/main/java/org/apache/ibatis/annotations/Lang.java
  src/main/java/org/apache/ibatis/annotations/Many.java
  src/main/java/org/apache/ibatis/annotations/MapKey.java
  src/main/java/org/apache/ibatis/annotations/Mapper.java
  src/main/java/org/apache/ibatis/annotations/One.java
  src/main/java/org/apache/ibatis/annotations/Options.java
  src/main/java/org/apache/ibatis/annotations/Param.java
  src/main/java/org/apache/ibatis/annotations/Property.java
  src/main/java/org/apache/ibatis/annotations/Result.java
  src/main/java/org/apache/ibatis/annotations/ResultMap.java
  src/main/java/org/apache/ibatis/annotations/ResultType.java
  src/main/java/org/apache/ibatis/annotations/Results.java
  src/main/java/org/apache/ibatis/annotations/Select.java
  src/main/java/org/apache/ibatis/annotations/SelectKey.java
  src/main/java/org/apache/ibatis/annotations/SelectProvider.java
  src/main/java/org/apache/ibatis/annotations/TypeDiscriminator.java
  src/main/java/org/apache/ibatis/annotations/Update.java
  src/main/java/org/apache/ibatis/annotations/UpdateProvider.java
  src/main/java/org/apache/ibatis/plugin/Intercepts.java
  src/main/java/org/apache/ibatis/plugin/Signature.java
  src/main/java/org/apache/ibatis/type/Alias.java
  src/main/java/org/apache/ibatis/type/MappedJdbcTypes.java
  src/main/java/org/apache/ibatis/type/MappedTypes.java
Labels: documentation

#1698 Support repeatable annotation on `@Arg` and `@Result`
  src/main/java/org/apache/ibatis/annotations/Arg.java
  src/main/java/org/apache/ibatis/annotations/Result.java
  src/main/java/org/apache/ibatis/builder/annotation/MapperAnnotationBuilder.java
  src/test/java/org/apache/ibatis/binding/BindingTest.java
  src/test/java/org/apache/ibatis/binding/BoundAuthorMapper.java
Labels: enhancement
