Repository mybatis/mybatis-3, pull requests merged in 2019-06, with the labels that each got.

#1568 add unit tests for ResolverUtil.
  src/test/java/org/apache/ibatis/io/ResolverUtilTest.java
Labels: waiting for feedback

#1521 Support LIMIT and OFFSET on SQL class
  src/main/java/org/apache/ibatis/jdbc/AbstractSQL.java
  src/site/es/xdoc/statement-builders.xml
  src/site/ja/xdoc/statement-builders.xml
  src/site/ko/xdoc/statement-builders.xml
  src/site/xdoc/statement-builders.xml
  src/site/zh/xdoc/statement-builders.xml
  src/test/java/org/apache/ibatis/jdbc/SQLTest.java
Labels: enhancement

#1575 Include statement ID in the error message when a referenced result map is missing
  src/main/java/org/apache/ibatis/builder/MapperBuilderAssistant.java
  src/test/java/org/apache/ibatis/builder/ProblemResultMapper.xml
  src/test/java/org/apache/ibatis/builder/XmlMapperBuilderTest.java
Labels: enhancement

#1577 Avoid registration of built-in typehandler using reflection
  src/main/java/org/apache/ibatis/type/TypeHandlerRegistry.java
Labels: polishing

#1579 All override methods must be added @override
  src/main/java/org/apache/ibatis/datasource/pooled/PooledDataSource.java
  src/main/java/org/apache/ibatis/datasource/unpooled/UnpooledDataSource.java
  src/main/java/org/apache/ibatis/session/Configuration.java
  src/test/java/org/apache/ibatis/autoconstructor/ExtensiveSubject.java
Labels: polishing

#1580 remove unnecessary interface modifier
  src/test/java/org/apache/ibatis/submitted/blocking_cache/PersonMapper.java
  src/test/java/org/apache/ibatis/submitted/cache/PersonMapper.java
  src/test/java/org/apache/ibatis/submitted/cglib_lazy_error/PersonMapper.java
  src/test/java/org/apache/ibatis/submitted/column_forwarding/Mapper.java
  src/test/java/org/apache/ibatis/submitted/complex_column/PersonMapper.java
  src/test/java/org/apache/ibatis/submitted/default_method/Mapper.java
  src/test/java/org/apache/ibatis/submitted/deferload_common_property/ChildMapper.java
  src/test/java/org/apache/ibatis/submitted/deferload_common_property/FatherMapper.java
  src/test/java/org/apache/ibatis/submitted/disallowdotsonnames/PersonMapper.java
  src/test/java/org/apache/ibatis/submitted/enumtypehandler_on_map/PersonMapper.java
  src/test/java/org/apache/ibatis/submitted/extends_with_constructor/StudentConstructorMapper.java
  src/test/java/org/apache/ibatis/submitted/extends_with_constructor/StudentMapper.java
  src/test/java/org/apache/ibatis/submitted/extends_with_constructor/TeacherMapper.java
  src/test/java/org/apache/ibatis/submitted/flush_statement_npe/PersonMapper.java
  src/test/java/org/apache/ibatis/submitted/force_flush_on_select/PersonMapper.java
  src/test/java/org/apache/ibatis/submitted/heavy_initial_load/ThingMapper.java
  src/test/java/org/apache/ibatis/submitted/immutable_constructor/ImmutablePOJOMapper.java
  src/test/java/org/apache/ibatis/submitted/lazy_immutable/ImmutablePOJOMapper.java
  src/test/java/org/apache/ibatis/submitted/lazyload_common_property/ChildMapper.java
  src/test/java/org/apache/ibatis/submitted/lazyload_common_property/FatherMapper.java
  src/test/java/org/apache/ibatis/submitted/lazyload_common_property/GrandFatherMapper.java
  src/test/java/org/apache/ibatis/submitted/map_class_name_conflict/PersonMapper.java
  src/test/java/org/apache/ibatis/submitted/mapper_type_parameter/BaseMapper.java
  src/test/java/org/apache/ibatis/submitted/multiple_discriminator/PersonMapper.java
  src/test/java/org/apache/ibatis/submitted/not_null_column/FatherMapper.java
  src/test/java/org/apache/ibatis/submitted/ognl_enum/PersonMapper.java
  src/test/java/org/apache/ibatis/submitted/order_prefix_removed/PersonMapper.java
  src/test/java/org/apache/ibatis/submitted/parent_reference_3level/Mapper.java
  src/test/java/org/apache/ibatis/submitted/serializecircular/AttributeMapper.java
  src/test/java/org/apache/ibatis/submitted/serializecircular/DepartmentMapper.java
  src/test/java/org/apache/ibatis/submitted/serializecircular/PersonMapper.java
  src/test/java/org/apache/ibatis/submitted/substitution_in_annots/SubstitutionInAnnotsMapper.java
  src/test/java/org/apache/ibatis/submitted/xml_references/PersonMapper.java
  src/test/java/org/apache/ibatis/submitted/xml_references/PersonMapper2.java
Labels: polishing

#1582 Support FETCH FIRST on SQL class
  src/main/java/org/apache/ibatis/jdbc/AbstractSQL.java
  src/site/es/xdoc/statement-builders.xml
  src/site/ja/xdoc/statement-builders.xml
  src/site/ko/xdoc/statement-builders.xml
  src/site/xdoc/statement-builders.xml
  src/site/zh/xdoc/statement-builders.xml
  src/test/java/org/apache/ibatis/jdbc/SQLTest.java
  src/test/java/org/apache/ibatis/submitted/sql/CreateDB-hsqldb.sql
  src/test/java/org/apache/ibatis/submitted/sql/CreateDB.sql
  src/test/java/org/apache/ibatis/submitted/sql/HsqldbSQLTest.java
  src/test/java/org/apache/ibatis/submitted/sql/Mapper.java
  src/test/java/org/apache/ibatis/submitted/sql/PostgresSQLTest.java
  src/test/java/org/apache/ibatis/submitted/sql/User.java
Labels: enhancement
