Repository mybatis/mybatis-3, pull requests merged in 2019-04, with the labels that each got.

#1508 Update dependencies
  pom.xml
Labels: polishing

#1478 JDBC 4.2 for LocalTime, LocalDate & LocalDateTime
  src/main/java/org/apache/ibatis/type/LocalDateTimeTypeHandler.java
  src/main/java/org/apache/ibatis/type/LocalDateTypeHandler.java
  src/main/java/org/apache/ibatis/type/LocalTimeTypeHandler.java
  src/test/java/org/apache/ibatis/submitted/localtime/CreateDB.sql
  src/test/java/org/apache/ibatis/submitted/localtime/LocalTimeTest.java
  src/test/java/org/apache/ibatis/submitted/localtime/Mapper.java
  src/test/java/org/apache/ibatis/submitted/localtime/Record.java
  src/test/java/org/apache/ibatis/submitted/localtime/mybatis-config.xml
  src/test/java/org/apache/ibatis/submitted/timezone_edge_case/CreateDB.sql
  src/test/java/org/apache/ibatis/submitted/timezone_edge_case/Mapper.java
  src/test/java/org/apache/ibatis/submitted/timezone_edge_case/Record.java
  src/test/java/org/apache/ibatis/submitted/timezone_edge_case/TimezoneEdgeCaseTest.java
  src/test/java/org/apache/ibatis/submitted/timezone_edge_case/mybatis-config.xml
  src/test/java/org/apache/ibatis/type/LocalDateTimeTypeHandlerTest.java
  src/test/java/org/apache/ibatis/type/LocalDateTypeHandlerTest.java
  src/test/java/org/apache/ibatis/type/LocalTimeTypeHandlerTest.java
Labels: bug

#1378 Fix and improvement for docs
  src/site/es/xdoc/java-api.xml
  src/site/ja/xdoc/java-api.xml
  src/site/ko/xdoc/java-api.xml
  src/site/xdoc/java-api.xml
  src/site/zh/xdoc/java-api.xml
Labels: documentation, polishing

#1530 Change to use try-with-resources on doc
  src/site/es/xdoc/getting-started.xml
  src/site/es/xdoc/java-api.xml
  src/site/fr/xdoc/getting-started.xml
  src/site/ja/xdoc/getting-started.xml
  src/site/ja/xdoc/java-api.xml
  src/site/ko/xdoc/getting-started.xml
  src/site/ko/xdoc/java-api.xml
  src/site/xdoc/getting-started.xml
  src/site/xdoc/java-api.xml
  src/site/zh/xdoc/getting-started.xml
  src/site/zh/xdoc/java-api.xml
Labels: documentation, polishing
