Repository mybatis/mybatis-3, pull requests merged in 2020-07, with the labels that each got.

#1973 Added SQL_SERVER_SNAPSHOT value to TransactionIsolationLevel enum
  src/main/java/org/apache/ibatis/session/TransactionIsolationLevel.java
Labels: enhancement

#1885 Optimization code
  src/main/java/org/apache/ibatis/io/DefaultVFS.java
Labels: polishing

#1972 Modify Array Size
  src/main/java/org/apache/ibatis/plugin/Plugin.java
Labels: polishing

#1994 Update link to Java Logging documentation
  src/site/es/xdoc/logging.xml
  src/site/ja/xdoc/logging.xml
  src/site/ko/xdoc/logging.xml
  src/site/xdoc/logging.xml
  src/site/zh/xdoc/logging.xml
Labels: documentation
