Repository mybatis/mybatis-3, pull requests merged in 2025-01, with the labels that each got.

#1494 Improve Cursor Closeable behavior
  src/main/java/org/apache/ibatis/cursor/Cursor.java
  src/main/java/org/apache/ibatis/session/defaults/DefaultSqlSession.java
  src/test/java/org/apache/ibatis/binding/BindingTest.java
  src/test/java/org/apache/ibatis/submitted/cursor_simple/CursorSimpleTest.java
  src/test/java/org/apache/ibatis/submitted/cursor_simple/PostgresCursorTest.java
Labels: enhancement, no backward compatibility

#3380 TypeParameterResolver : refactoring, improvements
  src/main/java/org/apache/ibatis/reflection/TypeParameterResolver.java
Labels: polishing

#3383 Replace deprecated `isAccessible()` with `canAccess()`
  src/main/java/org/apache/ibatis/executor/loader/ResultLoaderMap.java
  src/main/java/org/apache/ibatis/scripting/xmltags/OgnlMemberAccess.java
  src/test/java/org/apache/ibatis/submitted/custom_collection_handling/CustomObjectFactory.java
Labels: polishing

#3384 Pass docker image name to constructors
  src/test/java/org/apache/ibatis/testcontainers/MysqlContainer.java
  src/test/java/org/apache/ibatis/testcontainers/PgContainer.java
Labels: polishing

#3387 oracle implicit cursor workaround
  pom.xml
  src/main/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandler.java
  src/test/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandlerTest.java
  src/test/java/org/apache/ibatis/submitted/oracle_implicit_cursor/Author.java
  src/test/java/org/apache/ibatis/submitted/oracle_implicit_cursor/Book.java
  src/test/java/org/apache/ibatis/submitted/oracle_implicit_cursor/Mapper.java
  src/test/java/org/apache/ibatis/submitted/oracle_implicit_cursor/OracleImplicitCursorTest.java
  src/test/java/org/apache/ibatis/testcontainers/OracleTestContainer.java
  src/test/resources/org/apache/ibatis/submitted/oracle_implicit_cursor/CreateDB.sql
  src/test/resources/org/apache/ibatis/submitted/oracle_implicit_cursor/Mapper.xml
Labels: enhancement

#3386 Update configuration setting to change case and Chinese Translation
  src/site/es/xdoc/configuration.xml
  src/site/ja/xdoc/configuration.xml
  src/site/ko/xdoc/configuration.xml
  src/site/markdown/configuration.md
  src/site/zh_CN/xdoc/configuration.xml
Labels: 🌏 doc-zh

#2941 typo: fix some typo
  src/test/java/org/apache/ibatis/binding/BindingTest.java
  src/test/java/org/apache/ibatis/binding/BoundBlogMapper.java
  src/test/java/org/apache/ibatis/executor/loader/CglibProxyTest.java
  src/test/java/org/apache/ibatis/executor/loader/JavassistProxyTest.java
  src/test/java/org/apache/ibatis/executor/loader/SerializableProxyTest.java
  src/test/java/org/apache/ibatis/io/ExternalResourcesTest.java
  src/test/java/org/apache/ibatis/jdbc/ScriptRunnerTest.java
  src/test/java/org/apache/ibatis/mapping/ResultMappingTest.java
  src/test/java/org/apache/ibatis/submitted/automapping/AutomappingTest.java
  src/test/java/org/apache/ibatis/submitted/force_flush_on_select/ForceFlushOnSelectTest.java
  src/test/java/org/apache/ibatis/submitted/keygen/Jdbc3KeyGeneratorTest.java
  src/test/java/org/apache/ibatis/submitted/lazy_properties/LazyPropertiesTest.java
  src/test/java/org/apache/ibatis/submitted/result_handler/ResultHandlerTest.java
  src/test/java/org/apache/ibatis/type/SqlTimestampTypeHandlerTest.java
Labels: waiting for feedback

#3378 When `javaType` has not (or partially) been specified, determine the best matching constructor
  src/main/java/org/apache/ibatis/builder/MapperBuilderAssistant.java
  src/main/java/org/apache/ibatis/builder/ResultMappingConstructorResolver.java
  src/main/java/org/apache/ibatis/builder/annotation/MapperAnnotationBuilder.java
  src/main/java/org/apache/ibatis/builder/xml/XMLMapperBuilder.java
  src/main/java/org/apache/ibatis/mapping/ResultMap.java
  src/main/java/org/apache/ibatis/mapping/ResultMapping.java
  src/test/java/org/apache/ibatis/builder/ResultMappingConstructorResolverTest.java
  src/test/java/org/apache/ibatis/submitted/auto_type_from_non_ambiguous_constructor/Account.java
  src/test/java/org/apache/ibatis/submitted/auto_type_from_non_ambiguous_constructor/Account1.java
  src/test/java/org/apache/ibatis/submitted/auto_type_from_non_ambiguous_constructor/Account2.java
  src/test/java/org/apache/ibatis/submitted/auto_type_from_non_ambiguous_constructor/Account3.java
  src/test/java/org/apache/ibatis/submitted/auto_type_from_non_ambiguous_constructor/Account4.java
  src/test/java/org/apache/ibatis/submitted/auto_type_from_non_ambiguous_constructor/AutoTypeFromNonAmbiguousConstructorFailingTest.java
  src/test/java/org/apache/ibatis/submitted/auto_type_from_non_ambiguous_constructor/AutoTypeFromNonAmbiguousConstructorTest.java
  src/test/java/org/apache/ibatis/submitted/auto_type_from_non_ambiguous_constructor/FailingMapper.java
  src/test/java/org/apache/ibatis/submitted/auto_type_from_non_ambiguous_constructor/Mapper.java
  src/test/java/org/apache/ibatis/submitted/auto_type_from_non_ambiguous_constructor/Mapper1.java
  src/test/resources/org/apache/ibatis/immutable/ImmutableBlogMapper.xml
  src/test/resources/org/apache/ibatis/submitted/auto_type_from_non_ambiguous_constructor/CreateDB.sql
  src/test/resources/org/apache/ibatis/submitted/auto_type_from_non_ambiguous_constructor/FailingMapper.xml
  src/test/resources/org/apache/ibatis/submitted/auto_type_from_non_ambiguous_constructor/Mapper.xml
  src/test/resources/org/apache/ibatis/submitted/auto_type_from_non_ambiguous_constructor/mybatis-config-failing.xml
  src/test/resources/org/apache/ibatis/submitted/auto_type_from_non_ambiguous_constructor/mybatis-config.xml
Labels: 🔩 constructor
